### ISSUE TITLE
iOS : Argument 4 (NSNumber) of WifiManager.connectToProtectedSSID is marked as nullable

### ISSUE THREAD

**Issue by anuragipankaj** [JuanSeBestia/react-native-wifi-reborn#396] opened 2024-08-09 04:16 UTC
i'm facing this iOS issue in the latest version of react native wifi reborn package while calling the function :

**WifiManager.connectToProtectedSSID**

this is how I'm using it:

 WifiManager.connectToProtectedSSID(ssid, API.pIDevicePassword, false)

I think this is an issue in Pod file content where it is asking a parameter to be marked as nullable. Please suggest and provide guidance on how to fix it.

Argument 4 (NSNumber) of WifiManager.connectToProtectedSSID is marked as nullable but React requires that all NSNumber arguments are explicitly marked as `nonnull` to ensure compatibility with Android.

RCTLogArgumentError(RCTModuleMethod*, unsigned long, objc_object*, char const*)
    RCTModuleMethod.mm:67
-[RCTModuleMethod processMethodSignature]
-[RCTModuleMethod invokeWithBridge:module:arguments:]
facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&, int, (anonymous namespace)::SchedulingContext)
facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)::$_0::operator()() const
invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_lane_serial_drain
_dispatch_lane_invoke
_dispatch_root_queue_drain_deferred_wlh
_dispatch_workloop_worker_thread
_pthread_wqthread
start_wqthread

**Comment by DavideViolante** [comment] 2024-08-09 15:32
I think duplicate of https://github.com/JuanSeBestia/react-native-wifi-reborn/issues/379 and so I think this is a verified issue since v4.12.0, maybe since this change https://github.com/JuanSeBestia/react-native-wifi-reborn/commit/b5bdb35f5c51c35e2b8a4d50a9474cd396e40407

**Comment by nrsleonardo** [comment] 2024-08-25 01:46
same here.
using v4.11.0 with no issues.

**Comment by DavideViolante** [comment] 2024-08-28 07:39
Can someone on this thread can test the PR? https://github.com/JuanSeBestia/react-native-wifi-reborn/pull/397

**Closed** 2024-09-12 15:10 UTC
